<?php

/**
 * Country / area calling codes for phone verification UI (digits only, no leading +).
 * National number is entered separately; full E.164 is built as +{code}{national}.
 * Expanded per "Notes for System Issues" — must allow buyers/sellers from other
 * countries to register and verify their phone.
 */
return [
    ['code' => '1242', 'label' => 'Bahamas (+1242)'],
    ['code' => '1', 'label' => 'United States / Canada (+1)'],
    ['code' => '44', 'label' => 'United Kingdom (+44)'],
    // Caribbean
    ['code' => '1246', 'label' => 'Barbados (+1246)'],
    ['code' => '1876', 'label' => 'Jamaica (+1876)'],
    ['code' => '1268', 'label' => 'Antigua & Barbuda (+1268)'],
    ['code' => '1264', 'label' => 'Anguilla (+1264)'],
    ['code' => '1284', 'label' => 'British Virgin Islands (+1284)'],
    ['code' => '1340', 'label' => 'US Virgin Islands (+1340)'],
    ['code' => '1345', 'label' => 'Cayman Islands (+1345)'],
    ['code' => '1441', 'label' => 'Bermuda (+1441)'],
    ['code' => '1473', 'label' => 'Grenada (+1473)'],
    ['code' => '1649', 'label' => 'Turks & Caicos (+1649)'],
    ['code' => '1664', 'label' => 'Montserrat (+1664)'],
    ['code' => '1721', 'label' => 'Sint Maarten (+1721)'],
    ['code' => '1758', 'label' => 'Saint Lucia (+1758)'],
    ['code' => '1767', 'label' => 'Dominica (+1767)'],
    ['code' => '1784', 'label' => 'St Vincent & the Grenadines (+1784)'],
    ['code' => '1809', 'label' => 'Dominican Republic (+1809)'],
    ['code' => '1829', 'label' => 'Dominican Republic (+1829)'],
    ['code' => '1849', 'label' => 'Dominican Republic (+1849)'],
    ['code' => '1868', 'label' => 'Trinidad & Tobago (+1868)'],
    ['code' => '1869', 'label' => 'St Kitts & Nevis (+1869)'],
    ['code' => '53', 'label' => 'Cuba (+53)'],
    ['code' => '509', 'label' => 'Haiti (+509)'],
    // Americas
    ['code' => '52', 'label' => 'Mexico (+52)'],
    ['code' => '54', 'label' => 'Argentina (+54)'],
    ['code' => '55', 'label' => 'Brazil (+55)'],
    ['code' => '56', 'label' => 'Chile (+56)'],
    ['code' => '57', 'label' => 'Colombia (+57)'],
    ['code' => '58', 'label' => 'Venezuela (+58)'],
    ['code' => '51', 'label' => 'Peru (+51)'],
    // Europe
    ['code' => '33', 'label' => 'France (+33)'],
    ['code' => '34', 'label' => 'Spain (+34)'],
    ['code' => '39', 'label' => 'Italy (+39)'],
    ['code' => '49', 'label' => 'Germany (+49)'],
    ['code' => '31', 'label' => 'Netherlands (+31)'],
    ['code' => '32', 'label' => 'Belgium (+32)'],
    ['code' => '41', 'label' => 'Switzerland (+41)'],
    ['code' => '43', 'label' => 'Austria (+43)'],
    ['code' => '46', 'label' => 'Sweden (+46)'],
    ['code' => '47', 'label' => 'Norway (+47)'],
    ['code' => '45', 'label' => 'Denmark (+45)'],
    ['code' => '358', 'label' => 'Finland (+358)'],
    ['code' => '351', 'label' => 'Portugal (+351)'],
    ['code' => '353', 'label' => 'Ireland (+353)'],
    ['code' => '30', 'label' => 'Greece (+30)'],
    ['code' => '7', 'label' => 'Russia / Kazakhstan (+7)'],
    ['code' => '48', 'label' => 'Poland (+48)'],
    // Asia
    ['code' => '86', 'label' => 'China (+86)'],
    ['code' => '81', 'label' => 'Japan (+81)'],
    ['code' => '82', 'label' => 'South Korea (+82)'],
    ['code' => '91', 'label' => 'India (+91)'],
    ['code' => '92', 'label' => 'Pakistan (+92)'],
    ['code' => '880', 'label' => 'Bangladesh (+880)'],
    ['code' => '94', 'label' => 'Sri Lanka (+94)'],
    ['code' => '60', 'label' => 'Malaysia (+60)'],
    ['code' => '65', 'label' => 'Singapore (+65)'],
    ['code' => '66', 'label' => 'Thailand (+66)'],
    ['code' => '84', 'label' => 'Vietnam (+84)'],
    ['code' => '62', 'label' => 'Indonesia (+62)'],
    ['code' => '63', 'label' => 'Philippines (+63)'],
    ['code' => '852', 'label' => 'Hong Kong (+852)'],
    ['code' => '886', 'label' => 'Taiwan (+886)'],
    ['code' => '90', 'label' => 'Turkey (+90)'],
    ['code' => '966', 'label' => 'Saudi Arabia (+966)'],
    ['code' => '971', 'label' => 'United Arab Emirates (+971)'],
    ['code' => '972', 'label' => 'Israel (+972)'],
    ['code' => '974', 'label' => 'Qatar (+974)'],
    // Africa
    ['code' => '20', 'label' => 'Egypt (+20)'],
    ['code' => '27', 'label' => 'South Africa (+27)'],
    ['code' => '234', 'label' => 'Nigeria (+234)'],
    ['code' => '254', 'label' => 'Kenya (+254)'],
    ['code' => '233', 'label' => 'Ghana (+233)'],
    // Oceania
    ['code' => '61', 'label' => 'Australia (+61)'],
    ['code' => '64', 'label' => 'New Zealand (+64)'],
];
